import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getOrCreateUser } from "@/lib/auth";
import type { APIResponse, DailyPlan, GroceryItem, FoodItem, Meal } from "@/types";

export async function GET(
  _req: Request,
  { params }: { params: { id: string } }
) {
  try {
    const user = await getOrCreateUser();
    if (!user) {
      return NextResponse.json<APIResponse<never>>(
        { success: false, error: "Unauthorized" },
        { status: 401 }
      );
    }

    const mealPlan = await prisma.mealPlan.findFirst({
      where: { id: params.id, userId: user.id, deletedAt: null },
    });

    if (!mealPlan) {
      return NextResponse.json<APIResponse<never>>(
        { success: false, error: "Meal plan not found" },
        { status: 404 }
      );
    }

    const meals = mealPlan.meals as unknown as DailyPlan[];
    const groceryList = mealPlan.groceryList as unknown as GroceryItem[];

    // Generate text-based "PDF" content
    const lines: string[] = [];
    lines.push("═══════════════════════════════════════════════");
    lines.push("           FITPLAN AI — MEAL PLAN");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");
    lines.push(`Plan Type: ${mealPlan.planType}`);
    lines.push(`Fitness Goal: ${mealPlan.fitnessGoal}`);
    lines.push(`Dietary Preference: ${mealPlan.dietaryPreference}`);
    lines.push(`Target Calories: ${mealPlan.targetCalories} kcal/day`);
    lines.push(`Macros: ${mealPlan.proteinGrams}g protein / ${mealPlan.carbGrams}g carbs / ${mealPlan.fatGrams}g fat`);
    lines.push(`Daily Budget: ${mealPlan.budgetCurrency} ${mealPlan.totalDailyCost}`);
    lines.push("");

    for (const day of meals) {
      lines.push("───────────────────────────────────────────────");
      lines.push(`Day ${day.day}: ${day.dayName}`);
      lines.push(`  Total: ${day.totalCalories} kcal | Cost: ${mealPlan.budgetCurrency} ${day.totalCost}`);
      lines.push("───────────────────────────────────────────────");

      for (const meal of day.meals as Meal[]) {
        lines.push("");
        lines.push(`  🍴 ${meal.name} (${meal.totalCalories} kcal | ${mealPlan.budgetCurrency} ${meal.estimatedCost})`);
        lines.push(`     Protein: ${meal.totalProtein}g | Carbs: ${meal.totalCarbs}g | Fat: ${meal.totalFat}g`);
        lines.push("");

        for (const item of meal.foodItems as FoodItem[]) {
          lines.push(`     - ${item.name}: ${item.quantity} (${item.calories} kcal)`);
        }

        lines.push("");
        lines.push(`     Instructions: ${meal.cookingInstructions}`);
      }
      lines.push("");
    }

    lines.push("");
    lines.push("═══════════════════════════════════════════════");
    lines.push("           GROCERY LIST");
    lines.push("═══════════════════════════════════════════════");
    lines.push("");

    const grouped: Record<string, GroceryItem[]> = {};
    for (const item of groceryList) {
      const cat = item.category ?? "Other";
      if (!grouped[cat]) grouped[cat] = [];
      grouped[cat].push(item);
    }

    for (const [category, items] of Object.entries(grouped)) {
      lines.push(`  ${category}:`);
      for (const item of items) {
        lines.push(`    - ${item.name}: ${item.quantity} (${mealPlan.budgetCurrency} ${item.estimatedCost})`);
      }
      lines.push("");
    }

    lines.push("───────────────────────────────────────────────");
    lines.push(`Generated by FitPlan AI on ${new Date(mealPlan.createdAt).toLocaleDateString()}`);

    const content = lines.join("\n");

    return new Response(content, {
      status: 200,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="meal-plan-${mealPlan.id}.txt"`,
      },
    });
  } catch (error) {
    console.error("Download error:", error);
    return NextResponse.json<APIResponse<never>>(
      { success: false, error: "Internal server error" },
      { status: 500 }
    );
  }
}
